# Spotify(>=iOS15) - Nextin 版
# 2025.06.27 部分解锁premium,音质不能设置为超高(建议登录后再打开脚本,重启app等待脚本生效)
# 源仓库 https://github.com/app2smile/rules
# 功能: 1.去除播放广告 2.歌手/专辑列表正常展示 3.去除随机播放

[Script]
# 1) 改写 artist/album 请求 URL: platform=iphone -> platform=ipad
spotify-json = type=http-request,pattern=^https:\/\/(?:[^\/]+\.)*spotify\.com(?::443)?\/(?:artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/fyylflh/nextinrule/main/spotify-json.js,script-update-interval=0,enable=true

# 2) 删除 customize 请求的 if-none-match 头,避免 304 让响应脚本拿不到 body
spotify-header = type=http-request,pattern=^https:\/\/(?:[^\/]+\.)*spotify\.com(?::443)?\/user-customization-service\/v1\/customize$,requires-body=0,script-path=https://raw.githubusercontent.com/fyylflh/nextinrule/main/spotify-qx-header.js,script-update-interval=0,enable=true

# 3) 改写 bootstrap / customize 的 protobuf 响应
spotify-proto = type=http-response,pattern=^https:\/\/(?:[^\/]+\.)*spotify\.com(?::443)?\/(?:bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)(?:\?.*)?$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/fyylflh/nextinrule/main/spotify-proto.js,script-update-interval=0,enable=true

[MITM]
hostname = *.spotify.com, spclient.wg.spotify.com, *.wg.spotify.com
