[URL Rewrite]
^https:\/\/(((?:[^\/]+\.)*spotify\.com)(?::443)?\/(?:artistview\/v1\/artist|album-entity-view\/v2\/album)\/.*[?&])platform=iphone(.*)$ https://$1platform=ipad$3 302

[Script]
spotify-proto = type=http-response,pattern=^https:\/\/(?:[^\/]+\.)*spotify\.com(:443)?\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)(\?.*)?$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/fyylflh/nextinrule/main/spotify-proto.js,script-update-interval=0,enable=true

[MITM]
hostname = spclient.wg.spotify.com, *.wg.spotify.com, *.spotify.com, *spclient.spotify.com
